### ISSUE TITLE
/home/gitea/gitea: line 1: 404: command not found

### ISSUE THREAD

**Issue by niiku** [rhpds/openshift-gitea-image#1]
First of all, thank you for this greate template! Sadly, in your latest release (1.5.0) the /home/gitea/gitea file  is somehow broken, because it only contains `404 Not Found`. I rebuild the image locally and everything works fine so I think all you need to do is rebuild and push it again. Maybe the release wasn't available on `https://dl.gitea.io/gitea/` when you build it.

**Comment by wkulhanek** [comment]
We are on 1.11.3 now. So hopefully this is fixed. Please reopen if not.
