### ISSUE TITLE
Who is maintainer of this package?

### ISSUE THREAD

**Issue by 6543** [rhpds/openshift-gitea-image#14]
@wkulhanek only you?

If you have an matrix account it would be nice to know so I can invite you to the "gitea package maintainers" room

**Comment by wkulhanek** [comment]
Yes. Right now it is only me. I am not familiar with matrix accounts though.

**Comment by 6543** [comment]
@wkulhanek well that's fine ... if you like to join at some point just send me your account to `6543 @ obermui.de`
